name: exch_app
description: A modern, minimal, real-time currency converter
publish_to: 'none'

version: 0.1.3+5

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter


  cupertino_icons: ^1.0.6
  dio: ^5.4.0
  easy_debounce: ^2.0.3
  firebase_analytics: ^11.4.1
  firebase_core: ^3.5.0
  firebase_crashlytics: ^4.1.2
  firebase_messaging: ^15.2.4
  flutter_local_notifications: ^19.0.0
  flutter_svg: ^2.0.10+1
  fluttertoast: ^8.2.6
  freezed_annotation: ^2.4.4
  get_it: ^7.7.0
  intl: ^0.20.2
  internet_connection_checker_plus: ^2.7.0
  json_annotation: ^4.9.0
  package_info_plus: ^8.0.2
  shadcn_ui: ^0.39.2
  shared_preferences: ^2.3.2
  toggle_switch: ^2.3.0
  upgrader: ^11.3.1
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_launcher_icons: ^0.14.1

  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  freezed: ^2.5.7
  build_runner: ^2.4.13
  json_serializable: ^6.9.0
  
flutter_launcher_icons:
  android: "ic_launcher"
  min_sdk_android: 21
  image_path_android: "assets/images/logo.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/images/logo.png"
  ios: true
  image_path_ios: "assets/images/logo.png"
  remove_alpha_ios: true
  background_color_ios: "#ffffff"

flutter:
  generate: true
  uses-material-design: true

  
  assets:
    - assets/images/